/**
 * Trade journal (spec §18) — the permanent out-of-sample evaluation dataset.
 *
 * THE CENTRAL RULE: **predictions are append-only and are never rewritten after a model update.**
 * The moment historical predictions can be regenerated by a newer model, the record stops being
 * out-of-sample and becomes a description of the current model's opinion about the past. This
 * project already has the cautionary case — every claim that later collapsed (94.7% direction, the
 * T10 lookahead, the MINIMAL prune) was caught by comparing a frozen prediction against what
 * actually happened.
 *
 * Every row therefore carries the full config chain that produced it (model version, calibrator,
 * sizing curve, risk limits, scoring weights). A trade whose provenance cannot be reconstructed is a
 * trade that cannot be learned from.
 */

import type { TradeCandidate } from './candidate';

export interface JournalEntry {
  id: string;
  asset: string;
  direction: 'LONG' | 'SHORT';

  // --- provenance: frozen at prediction time, never updated ---
  signalTimestamp: number;
  decisionTimestamp: number;
  dataTimestamp: number;
  featureTimestamp: number;
  modelVersion: string;
  crashModelVersion: string;
  configChain: string;

  // --- the prediction, frozen ---
  entryPrice: number;
  stopPrice: number;
  targetPrice: number;
  holdingHorizonHours: number;
  predictedWinProbability: number;
  expectedValueR: number;
  payoffAsymmetry: number;
  confidence: number;
  crashProbability: number;
  crashRegime: string;
  recommendedPositionFraction: number;

  // --- outcome: written once, later ---
  actualEntryPrice: number | null;
  actualExitPrice: number | null;
  exitTimestamp: number | null;
  realizedR: number | null;
  realizedReturnPct: number | null;
  maxFavorableExcursionR: number | null;
  maxAdverseExcursionR: number | null;
  outcome: TradeOutcome | null;
}

export type TradeOutcome = 'target' | 'stop' | 'timeout' | 'manual_exit' | 'not_taken' | 'invalidated';

/** Build an immutable journal entry from a candidate. */
export function entryFromCandidate(c: TradeCandidate, id: string, signalTimestamp: number): JournalEntry {
  return {
    id, asset: c.asset, direction: c.direction,
    signalTimestamp,
    decisionTimestamp: c.provenance.decisionTimestamp,
    dataTimestamp: c.provenance.dataTimestamp,
    featureTimestamp: c.provenance.featureTimestamp,
    modelVersion: c.provenance.modelVersion,
    crashModelVersion: c.provenance.crashModelVersion,
    configChain: c.provenance.sizingConfigId,
    entryPrice: c.entryPrice, stopPrice: c.stopPrice, targetPrice: c.targetPrice,
    holdingHorizonHours: c.holdingHorizonHours,
    predictedWinProbability: c.payoff.winProbability,
    expectedValueR: c.payoff.expectedValueR,
    payoffAsymmetry: c.payoff.payoffAsymmetry,
    confidence: c.payoff.confidence,
    crashProbability: c.crashRisk.probability,
    crashRegime: c.crashRisk.regime,
    recommendedPositionFraction: c.recommendedPositionFraction,
    actualEntryPrice: null, actualExitPrice: null, exitTimestamp: null,
    realizedR: null, realizedReturnPct: null,
    maxFavorableExcursionR: null, maxAdverseExcursionR: null, outcome: null,
  };
}

export class JournalError extends Error {
  constructor(m: string) { super(m); this.name = 'JournalError'; }
}

/**
 * Attach an outcome. Refuses to overwrite one that already exists — the append-only rule enforced
 * at the point where it would actually be violated, since "just correcting" a resolved outcome is
 * how an OOS record quietly becomes an in-sample one.
 */
export function recordOutcome(
  entry: JournalEntry,
  outcome: {
    actualEntryPrice: number; actualExitPrice: number; exitTimestamp: number;
    maxFavorableExcursionR: number; maxAdverseExcursionR: number; outcome: TradeOutcome;
  },
): JournalEntry {
  if (entry.outcome !== null) {
    throw new JournalError(`entry ${entry.id} already resolved as '${entry.outcome}' — journal is append-only`);
  }
  const riskPerUnit = Math.abs(entry.entryPrice - entry.stopPrice);
  const signed = entry.direction === 'LONG'
    ? outcome.actualExitPrice - outcome.actualEntryPrice
    : outcome.actualEntryPrice - outcome.actualExitPrice;
  return {
    ...entry,
    ...outcome,
    realizedR: riskPerUnit > 0 ? signed / riskPerUnit : null,
    realizedReturnPct: outcome.actualEntryPrice > 0 ? (signed / outcome.actualEntryPrice) * 100 : null,
  };
}

/** Mark a prediction that was never acted on. Still valuable: it is an unbiased OOS observation. */
export function recordNotTaken(entry: JournalEntry, at: number): JournalEntry {
  if (entry.outcome !== null) throw new JournalError(`entry ${entry.id} already resolved`);
  return { ...entry, outcome: 'not_taken', exitTimestamp: at };
}

// ── Aggregate evaluation ──────────────────────────────────────────────────────

export interface JournalStats {
  n: number;
  resolved: number;
  hitRate: number;
  meanRealizedR: number;
  meanPredictedEvR: number;
  /** realized − predicted. The honesty number: persistently negative means the model oversells. */
  evError: number;
  totalR: number;
  maxAdverseR: number;
}

/**
 * Aggregate resolved trades. `not_taken` is excluded from performance but retained in the store —
 * it is evidence about the generator, not about execution.
 */
export function stats(entries: readonly JournalEntry[]): JournalStats {
  const resolved = entries.filter(e => e.outcome !== null && e.outcome !== 'not_taken' && e.realizedR !== null);
  const n = resolved.length;
  if (n === 0) {
    return { n: entries.length, resolved: 0, hitRate: NaN, meanRealizedR: NaN,
             meanPredictedEvR: NaN, evError: NaN, totalR: 0, maxAdverseR: NaN };
  }
  const realized = resolved.map(e => e.realizedR!);
  const meanRealized = realized.reduce((a, b) => a + b, 0) / n;
  const meanPredicted = resolved.reduce((a, e) => a + e.expectedValueR, 0) / n;
  return {
    n: entries.length,
    resolved: n,
    hitRate: resolved.filter(e => e.realizedR! > 0).length / n,
    meanRealizedR: meanRealized,
    meanPredictedEvR: meanPredicted,
    evError: meanRealized - meanPredicted,
    totalR: realized.reduce((a, b) => a + b, 0),
    maxAdverseR: Math.min(...resolved.map(e => e.maxAdverseExcursionR ?? 0)),
  };
}

/**
 * Slice by config chain, so a model or parameter change can be evaluated against its predecessor
 * on trades each one actually made — rather than by re-scoring history with the new model, which
 * is the failure mode this whole module exists to prevent.
 */
export function statsByConfig(entries: readonly JournalEntry[]): Record<string, JournalStats> {
  const byConfig: Record<string, JournalEntry[]> = {};
  for (const e of entries) (byConfig[e.configChain] ??= []).push(e);
  return Object.fromEntries(Object.entries(byConfig).map(([k, v]) => [k, stats(v)]));
}

/** Lazy table creation, matching the pattern used by `tracked_setups`. */
export const CREATE_TABLE_SQL = `
CREATE TABLE IF NOT EXISTS trade_journal (
  id TEXT PRIMARY KEY,
  asset TEXT NOT NULL,
  direction TEXT NOT NULL,
  signal_timestamp INTEGER NOT NULL,
  decision_timestamp INTEGER NOT NULL,
  data_timestamp INTEGER NOT NULL,
  feature_timestamp INTEGER NOT NULL,
  model_version TEXT NOT NULL,
  crash_model_version TEXT NOT NULL,
  config_chain TEXT NOT NULL,
  entry_price REAL NOT NULL,
  stop_price REAL NOT NULL,
  target_price REAL NOT NULL,
  holding_horizon_hours REAL NOT NULL,
  predicted_win_probability REAL NOT NULL,
  expected_value_r REAL NOT NULL,
  payoff_asymmetry REAL NOT NULL,
  confidence REAL NOT NULL,
  crash_probability REAL NOT NULL,
  crash_regime TEXT NOT NULL,
  recommended_position_fraction REAL NOT NULL,
  actual_entry_price REAL,
  actual_exit_price REAL,
  exit_timestamp INTEGER,
  realized_r REAL,
  realized_return_pct REAL,
  max_favorable_excursion_r REAL,
  max_adverse_excursion_r REAL,
  outcome TEXT
);
CREATE INDEX IF NOT EXISTS idx_journal_asset ON trade_journal(asset, signal_timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_journal_open ON trade_journal(outcome, signal_timestamp);
CREATE INDEX IF NOT EXISTS idx_journal_config ON trade_journal(config_chain, signal_timestamp DESC);
`;
