import { describe, expect, test } from 'vitest';
import { computeAllFeatures, type Candle as FullCandle } from '../src/scoring-full';
import { mlPredict } from '../src/ml-predict';
import { readFileSync, readdirSync, existsSync, mkdirSync } from 'fs';
import { join } from 'path';

/**
 * Worker ↔ BacktestEngine canonical parity tests.
 *
 * Each fixture is a frozen I/O snapshot generated by iOS BacktestEngine for a specific
 * (symbol, date). It contains the raw inputs that BacktestEngine fed to feature
 * computation AND the resulting feature dict + ML probability — those are the canonical
 * values the worker MUST reproduce on the same inputs.
 *
 * The model JSON the worker uses must equal what BacktestEngine produced features for; if
 * they diverge, both training canonical and live serving fall out of sync.
 *
 * Generation: iOS BacktestView → "Capture Parity Fixture" (Debug only) → user copies the
 * JSON from simulator's Documents/ml_exports/fixtures/ to test/fixtures/backtest-canonical/.
 *
 * Tolerance: 1e-7 absolute. Tighter than necessary for production but loose enough to
 * survive last-bit floating-point differences between Swift and TypeScript implementations.
 */

const FIXTURES_DIR = join(__dirname, 'fixtures', 'backtest-canonical');
const TOLERANCE_DECIMAL_PLACES = 7;  // 1e-7 absolute

interface ParityFixture {
    name: string;
    symbol: string;
    isCrypto: boolean;
    evalTimestampMs: number;
    inputs: {
        dailyCandles: FullCandle[];
        fourHCandles: FullCandle[];
        oneHCandles: FullCandle[];
        spyCandles: FullCandle[];
        iwmCandles: FullCandle[];
        sectorEtfCandles: FullCandle[];
        dxyCandles: FullCandle[];
        ethBtcCandles: FullCandle[];
        vix3mPrice: number;
        macroVix: number;
        macroDxyAboveEma20: number;
        derivSignals: {
            fundingSignal: number;
            oiSignal: number;
            takerSignal: number;
            crowdingSignal: number;
            derivativesCombined: number;
            fundingRateRaw: number;
            oiChangePct: number;
            takerRatioRaw: number;
            longPctRaw: number;
        };
        sentiment: {
            fearGreedIndex: number;
            fearGreedZone: number;
            ethBtcRatio: number;
            ethBtcDelta6: number;
            basisPct: number;
        };
        prevSnapshot: {
            dRsi: number;
            dAdx: number;
            hRsi: number;
            hAdx: number;
            hMacdHist: number;
            hRsiD1: number;
            hMacdD1: number;
            dAdxD1: number;
        } | null;
        darkPoolRatio: number | null;
        darkPoolZScore: number | null;
    };
    expected: {
        features: Record<string, number>;
        mlProbability: number;
    };
}

describe('Worker ↔ BacktestEngine canonical parity', () => {
    if (!existsSync(FIXTURES_DIR)) {
        mkdirSync(FIXTURES_DIR, { recursive: true });
    }
    const files = readdirSync(FIXTURES_DIR).filter(f => f.endsWith('.json'));

    if (files.length === 0) {
        test('no fixtures yet — generate via iOS BacktestView "Capture Parity Fixture"', () => {
            console.warn(`No fixtures found in ${FIXTURES_DIR}. Run iOS BacktestEngine in capture mode and copy the JSON files here.`);
            // Pass (no assertion) — the suite is just a stub until fixtures exist.
        });
        return;
    }

    for (const file of files) {
        const fixture = JSON.parse(readFileSync(join(FIXTURES_DIR, file), 'utf-8')) as ParityFixture;

        describe(fixture.name, () => {
            // Compute features once, share across all per-feature assertions.
            const darkPool = (fixture.inputs.darkPoolRatio !== null && fixture.inputs.darkPoolZScore !== null)
                ? { ratio: fixture.inputs.darkPoolRatio, zscore: fixture.inputs.darkPoolZScore }
                : undefined;

            const features = computeAllFeatures(
                fixture.inputs.dailyCandles,
                fixture.inputs.fourHCandles,
                fixture.inputs.oneHCandles,
                fixture.isCrypto,
                fixture.inputs.derivSignals,
                { vix: fixture.inputs.macroVix, dxyAboveEma20: fixture.inputs.macroDxyAboveEma20 },
                fixture.inputs.sentiment,
                fixture.inputs.prevSnapshot ?? undefined,
                fixture.inputs.spyCandles,
                darkPool,
                fixture.inputs.iwmCandles,
                fixture.inputs.sectorEtfCandles,
                fixture.inputs.dxyCandles,
                fixture.inputs.vix3mPrice,
                fixture.symbol,
            );

            // Skip temporal features that derive from `new Date()`/`now`: they reflect the
            // moment computeAllFeatures was CALLED, not the bar's eval time. In production
            // those align (cron runs at eval time). In tests the fixture's evalTime is in
            // the past, so worker computes "today" while fixture's expected is "eval day".
            // These are correct in production; we skip them in parity tests.
            const TEMPORAL_FEATURES = new Set(['dayOfWeek', 'hourBucket', 'isWeekend']);

            // Per-feature parity assertions
            for (const key of Object.keys(fixture.expected.features)) {
                if (TEMPORAL_FEATURES.has(key)) continue;
                test(`feature ${key}`, () => {
                    const expected = fixture.expected.features[key];
                    const actual = (features as any)[key];
                    if (typeof actual !== 'number' || !Number.isFinite(actual)) {
                        throw new Error(`worker did not produce a finite number for ${key}: got ${actual}`);
                    }
                    expect(actual).toBeCloseTo(expected, TOLERANCE_DECIMAL_PLACES);
                });
            }

            // ML probability parity (separate test so it shows distinctly)
            test('mlProbability', () => {
                const ml = mlPredict(features as Record<string, number>, fixture.isCrypto);
                expect(ml).toBeCloseTo(fixture.expected.mlProbability, TOLERANCE_DECIMAL_PLACES);
            });
        });
    }
});
