import Foundation

/// JSON shape for Worker ↔ BacktestEngine parity fixtures.
///
/// A fixture is a frozen I/O snapshot: BacktestEngine ran for one specific (symbol, date)
/// and produced these features + this ML probability from these inputs. The TS test in
/// `marketscope-worker/test/parity-vs-backtest.test.ts` reads the fixture, calls the worker's
/// `computeAllFeatures`/`mlPredict` on the same inputs, and asserts the output matches
/// within 1e-7 absolute tolerance for every feature.
///
/// Fixtures are GENERATED by iOS (BacktestEngine has the canonical training-time logic) and
/// CONSUMED by TS tests (worker is the live-inference implementation that must match).
///
/// Regenerate fixtures whenever BacktestEngine's feature math intentionally changes; the
/// fixture file should be committed to git so both sides are pinned to a known-good snapshot.
struct ParityFixture: Codable {
    let name: String
    let symbol: String
    let isCrypto: Bool
    /// Evaluation timestamp in milliseconds since epoch (UTC).
    let evalTimestampMs: Int64
    let inputs: ParityFixtureInputs
    let expected: ParityFixtureExpected
}

struct ParityFixtureInputs: Codable {
    let dailyCandles: [ParityCandle]
    let fourHCandles: [ParityCandle]
    let oneHCandles: [ParityCandle]
    let spyCandles: [ParityCandle]
    let iwmCandles: [ParityCandle]
    let sectorEtfCandles: [ParityCandle]
    let dxyCandles: [ParityCandle]
    let ethBtcCandles: [ParityCandle]
    let vix3mPrice: Double
    let macroVix: Double
    /// 1 if DXY > DXY_EMA20 at eval time, 0 otherwise.
    let macroDxyAboveEma20: Int
    let derivSignals: ParityDerivSignals
    let sentiment: ParitySentiment
    let prevSnapshot: ParityPrevSnapshot?
    /// Dark pool data for stocks. Nil for crypto (worker uses undefined).
    let darkPoolRatio: Double?
    let darkPoolZScore: Double?
}

struct ParityCandle: Codable {
    let time: Int64
    let open: Double
    let high: Double
    let low: Double
    let close: Double
    let volume: Double
}

struct ParityDerivSignals: Codable {
    let fundingSignal: Double
    let oiSignal: Double
    let takerSignal: Double
    let crowdingSignal: Double
    let derivativesCombined: Double
    let fundingRateRaw: Double
    let oiChangePct: Double
    let takerRatioRaw: Double
    let longPctRaw: Double
}

struct ParitySentiment: Codable {
    let fearGreedIndex: Double
    let fearGreedZone: Double
    let ethBtcRatio: Double
    let ethBtcDelta6: Double
    let basisPct: Double
}

struct ParityPrevSnapshot: Codable {
    let dRsi: Double
    let dAdx: Double
    let hRsi: Double
    let hAdx: Double
    let hMacdHist: Double
    /// 1-bar prior values for acceleration features.
    let hRsiD1: Double
    let hMacdD1: Double
    let dAdxD1: Double
}

struct ParityFixtureExpected: Codable {
    /// Dictionary of all 111 features as produced by BacktestEngine for this bar.
    let features: [String: Double]
    /// ML probability from MLScoring.predict on the same features.
    let mlProbability: Double
}

extension ParityCandle {
    init(from candle: Candle) {
        self.time = Int64(candle.time.timeIntervalSince1970 * 1000)
        self.open = candle.open
        self.high = candle.high
        self.low = candle.low
        self.close = candle.close
        self.volume = candle.volume
    }
}
